### ISSUE TITLE
Move resource999.s2z to 'settings' folder

### ISSUE THREAD

**Issue by xGitHubUser999x** [Xen0byte/Heroes-Of-Newerth-Mod-Manager#29]
Due to the new priority system (settings > KONGOR > game > base), it is necessary to create resource999.s2z in the 'settings' folder, and not in 'game' folder. Сhanges made by resource999.s2z can be overwritten by .s2z archives from 'KONGOR' folder, which makes honmods completely or partially inoperative.

**Comment by Xen0byte** [comment]
The priority order is `game < KONGOR < extensions < settings` (in order of how the executable reads resource directories) and the new resource file is created in the extensions directory overriding most of everything.

**Comment by xGitHubUser999x** [comment]
> The priority order is `game < KONGOR < extensions < settings` (in order of how the executable reads resource directories) and the new resource file is created in the `extensions` directory overriding most of everything.
Currently modman 1.4.1.0:
1) creates resource999.s2z in 'game' folder (as it was before), and not in 'extensions' folder.
2) sees honmods that are placed in C:\Heroes of Newerth x64\game\mods (as it was before) and does not see honmods that are placed in C:\Program Files\Heroes of Newerth x64\extensions\mods.
