### ISSUE TITLE
ModMan 1.4.1.0 creates resource999.s2z in 'game' folder, and not in 'extensions' folder

### ISSUE THREAD

**Issue by xGitHubUser999x** [Xen0byte/Heroes-Of-Newerth-Mod-Manager#30]
Currently modman 1.4.1.0:
1) creates resource999.s2z in 'game' folder (as it was before), and not in 'extensions' folder.
2) sees .honmod files that are placed in C:\Heroes of Newerth x64\game\mods (as it was before) and does not see .honmod files that are placed in C:\Program Files\Heroes of Newerth x64\extensions\mods.
3) CTRL+F (File-->Open Mod Folder) opens the mods folder in C:\Heroes of Newerth x64\game\mods (as it was before), and not in C:\Program Files\Heroes of Newerth x64\extensions\mods.

**Comment by Xen0byte** [comment]
1.4.1.0 is the pre-KONGOR version, uploaded for posterity. A new version will be released once I find some time to work on it.

**Comment by Xen0byte** [comment]
As a workaround, you can generate your mods resources file as you normally would, create an `extensions` directory in the HoN folder, and move the mods resources file there.
